// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlfx99l9eP_2YwR79luJsElXlY88PuIH0',
    appId: '1:31445281860:web:99b1015e5c64c5d9e4a011',
    messagingSenderId: '31445281860',
    projectId: 'school-management-963d2',
    authDomain: 'school-management-963d2.firebaseapp.com',
    storageBucket: 'school-management-963d2.appspot.com',
    measurementId: 'G-07HX9NNB0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKZF0fqka7GhUhsukUsHOd_85P_h9v6EQ',
    appId: '1:31445281860:android:af05210bb043703ae4a011',
    messagingSenderId: '31445281860',
    projectId: 'school-management-963d2',
    storageBucket: 'school-management-963d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsslsh5bXGsBoqdhL6z1LsKsuQvvYMpis',
    appId: '1:31445281860:ios:19907fc03ab26efae4a011',
    messagingSenderId: '31445281860',
    projectId: 'school-management-963d2',
    storageBucket: 'school-management-963d2.appspot.com',
    iosBundleId: 'com.example.schoolManagementTeacher',
  );
}
